/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bar2BarScoreRecord extends org.jooq.impl.TableRecordImpl<com.github.drinking_buddies.jooq.tables.records.Bar2BarScoreRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1834449843;

	/**
	 * Setter for <code>bar2_bar_score.bar_id</code>. 
	 */
	public void setBarId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>bar2_bar_score.bar_id</code>. 
	 */
	public java.lang.Integer getBarId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>bar2_bar_score.bar_score_id</code>. 
	 */
	public void setBarScoreId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>bar2_bar_score.bar_score_id</code>. 
	 */
	public java.lang.Integer getBarScoreId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.drinking_buddies.jooq.tables.Bar2BarScore.BAR2_BAR_SCORE.BAR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.drinking_buddies.jooq.tables.Bar2BarScore.BAR2_BAR_SCORE.BAR_SCORE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getBarId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getBarScoreId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Bar2BarScoreRecord
	 */
	public Bar2BarScoreRecord() {
		super(com.github.drinking_buddies.jooq.tables.Bar2BarScore.BAR2_BAR_SCORE);
	}

	/**
	 * Create a detached, initialised Bar2BarScoreRecord
	 */
	public Bar2BarScoreRecord(java.lang.Integer barId, java.lang.Integer barScoreId) {
		super(com.github.drinking_buddies.jooq.tables.Bar2BarScore.BAR2_BAR_SCORE);

		setValue(0, barId);
		setValue(1, barScoreId);
	}
}
