/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bar2BarCommentRecord extends org.jooq.impl.TableRecordImpl<com.github.drinking_buddies.jooq.tables.records.Bar2BarCommentRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 546647830;

	/**
	 * Setter for <code>bar2_bar_comment.id_barcomment</code>. 
	 */
	public void setIdBarcomment(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>bar2_bar_comment.id_barcomment</code>. 
	 */
	public java.lang.Integer getIdBarcomment() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>bar2_bar_comment.id_bar</code>. 
	 */
	public void setIdBar(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>bar2_bar_comment.id_bar</code>. 
	 */
	public java.lang.Integer getIdBar() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.drinking_buddies.jooq.tables.Bar2BarComment.BAR2_BAR_COMMENT.ID_BARCOMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.drinking_buddies.jooq.tables.Bar2BarComment.BAR2_BAR_COMMENT.ID_BAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdBarcomment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIdBar();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Bar2BarCommentRecord
	 */
	public Bar2BarCommentRecord() {
		super(com.github.drinking_buddies.jooq.tables.Bar2BarComment.BAR2_BAR_COMMENT);
	}

	/**
	 * Create a detached, initialised Bar2BarCommentRecord
	 */
	public Bar2BarCommentRecord(java.lang.Integer idBarcomment, java.lang.Integer idBar) {
		super(com.github.drinking_buddies.jooq.tables.Bar2BarComment.BAR2_BAR_COMMENT);

		setValue(0, idBarcomment);
		setValue(1, idBar);
	}
}
