/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BarRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.drinking_buddies.jooq.tables.records.BarRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, byte[], java.lang.String, java.lang.Integer, java.lang.Float, java.lang.Float> {

	private static final long serialVersionUID = -1091180308;

	/**
	 * Setter for <code>bar.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>bar.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>bar.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>bar.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>bar.photo</code>. 
	 */
	public void setPhoto(byte[] value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>bar.photo</code>. 
	 */
	public byte[] getPhoto() {
		return (byte[]) getValue(2);
	}

	/**
	 * Setter for <code>bar.website</code>. 
	 */
	public void setWebsite(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>bar.website</code>. 
	 */
	public java.lang.String getWebsite() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>bar.address_id</code>. 
	 */
	public void setAddressId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>bar.address_id</code>. 
	 */
	public java.lang.Integer getAddressId() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>bar.location_x</code>. 
	 */
	public void setLocationX(java.lang.Float value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>bar.location_x</code>. 
	 */
	public java.lang.Float getLocationX() {
		return (java.lang.Float) getValue(5);
	}

	/**
	 * Setter for <code>bar.location_y</code>. 
	 */
	public void setLocationY(java.lang.Float value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>bar.location_y</code>. 
	 */
	public java.lang.Float getLocationY() {
		return (java.lang.Float) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, byte[], java.lang.String, java.lang.Integer, java.lang.Float, java.lang.Float> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, byte[], java.lang.String, java.lang.Integer, java.lang.Float, java.lang.Float> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.drinking_buddies.jooq.tables.Bar.BAR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.github.drinking_buddies.jooq.tables.Bar.BAR.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field3() {
		return com.github.drinking_buddies.jooq.tables.Bar.BAR.PHOTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.github.drinking_buddies.jooq.tables.Bar.BAR.WEBSITE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.github.drinking_buddies.jooq.tables.Bar.BAR.ADDRESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Float> field6() {
		return com.github.drinking_buddies.jooq.tables.Bar.BAR.LOCATION_X;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Float> field7() {
		return com.github.drinking_buddies.jooq.tables.Bar.BAR.LOCATION_Y;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value3() {
		return getPhoto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getWebsite();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getAddressId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Float value6() {
		return getLocationX();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Float value7() {
		return getLocationY();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BarRecord
	 */
	public BarRecord() {
		super(com.github.drinking_buddies.jooq.tables.Bar.BAR);
	}

	/**
	 * Create a detached, initialised BarRecord
	 */
	public BarRecord(java.lang.Integer id, java.lang.String name, byte[] photo, java.lang.String website, java.lang.Integer addressId, java.lang.Float locationX, java.lang.Float locationY) {
		super(com.github.drinking_buddies.jooq.tables.Bar.BAR);

		setValue(0, id);
		setValue(1, name);
		setValue(2, photo);
		setValue(3, website);
		setValue(4, addressId);
		setValue(5, locationX);
		setValue(6, locationY);
	}
}
