/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BarScoreRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 1290671505;

	/**
	 * Setter for <code>bar_score.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>bar_score.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>bar_score.score</code>. 
	 */
	public void setScore(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>bar_score.score</code>. 
	 */
	public java.lang.Integer getScore() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>bar_score.post_time</code>. 
	 */
	public void setPostTime(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>bar_score.post_time</code>. 
	 */
	public java.lang.String getPostTime() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>bar_score.user_id</code>. 
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>bar_score.user_id</code>. 
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE.SCORE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE.POST_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getScore();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPostTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getUserId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BarScoreRecord
	 */
	public BarScoreRecord() {
		super(com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE);
	}

	/**
	 * Create a detached, initialised BarScoreRecord
	 */
	public BarScoreRecord(java.lang.Integer id, java.lang.Integer score, java.lang.String postTime, java.lang.Integer userId) {
		super(com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE);

		setValue(0, id);
		setValue(1, score);
		setValue(2, postTime);
		setValue(3, userId);
	}
}
