/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Beer2BeerTagRecord extends org.jooq.impl.TableRecordImpl<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1680802031;

	/**
	 * Setter for <code>beer2_beer_tag.beer_tag_id</code>. 
	 */
	public void setBeerTagId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>beer2_beer_tag.beer_tag_id</code>. 
	 */
	public java.lang.Integer getBeerTagId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>beer2_beer_tag.beer_id</code>. 
	 */
	public void setBeerId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>beer2_beer_tag.beer_id</code>. 
	 */
	public java.lang.Integer getBeerId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG.BEER_TAG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG.BEER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getBeerTagId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getBeerId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Beer2BeerTagRecord
	 */
	public Beer2BeerTagRecord() {
		super(com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG);
	}

	/**
	 * Create a detached, initialised Beer2BeerTagRecord
	 */
	public Beer2BeerTagRecord(java.lang.Integer beerTagId, java.lang.Integer beerId) {
		super(com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG);

		setValue(0, beerTagId);
		setValue(1, beerId);
	}
}
