/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Beer2BeerTagRecord extends org.jooq.impl.TableRecordImpl<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord> implements org.jooq.Record2<java.lang.Object, java.lang.Integer> {

	private static final long serialVersionUID = 1215483396;

	/**
	 * Setter for <code>beer2_beer_tag.beertag</code>. 
	 */
	public void setBeertag(java.lang.Object value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>beer2_beer_tag.beertag</code>. 
	 */
	public java.lang.Object getBeertag() {
		return (java.lang.Object) getValue(0);
	}

	/**
	 * Setter for <code>beer2_beer_tag.id_beer</code>. 
	 */
	public void setIdBeer(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>beer2_beer_tag.id_beer</code>. 
	 */
	public java.lang.Integer getIdBeer() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Object, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Object, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field1() {
		return com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG.BEERTAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG.ID_BEER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value1() {
		return getBeertag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIdBeer();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Beer2BeerTagRecord
	 */
	public Beer2BeerTagRecord() {
		super(com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG);
	}

	/**
	 * Create a detached, initialised Beer2BeerTagRecord
	 */
	public Beer2BeerTagRecord(java.lang.Object beertag, java.lang.Integer idBeer) {
		super(com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG);

		setValue(0, beertag);
		setValue(1, idBeer);
	}
}
