/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BuddyRecord extends org.jooq.impl.TableRecordImpl<com.github.drinking_buddies.jooq.tables.records.BuddyRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 2063526908;

	/**
	 * Setter for <code>buddy.user_id</code>. 
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>buddy.user_id</code>. 
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>buddy.buddy_id</code>. 
	 */
	public void setBuddyId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>buddy.buddy_id</code>. 
	 */
	public java.lang.Integer getBuddyId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.drinking_buddies.jooq.tables.Buddy.BUDDY.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.drinking_buddies.jooq.tables.Buddy.BUDDY.BUDDY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getBuddyId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BuddyRecord
	 */
	public BuddyRecord() {
		super(com.github.drinking_buddies.jooq.tables.Buddy.BUDDY);
	}

	/**
	 * Create a detached, initialised BuddyRecord
	 */
	public BuddyRecord(java.lang.Integer userId, java.lang.Integer buddyId) {
		super(com.github.drinking_buddies.jooq.tables.Buddy.BUDDY);

		setValue(0, userId);
		setValue(1, buddyId);
	}
}
