/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FavoriteBeerRecord extends org.jooq.impl.TableRecordImpl<com.github.drinking_buddies.jooq.tables.records.FavoriteBeerRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1400717714;

	/**
	 * Setter for <code>favorite_beer.user_id</code>. 
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>favorite_beer.user_id</code>. 
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>favorite_beer.beer_id</code>. 
	 */
	public void setBeerId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>favorite_beer.beer_id</code>. 
	 */
	public java.lang.Integer getBeerId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER.BEER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getBeerId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FavoriteBeerRecord
	 */
	public FavoriteBeerRecord() {
		super(com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER);
	}

	/**
	 * Create a detached, initialised FavoriteBeerRecord
	 */
	public FavoriteBeerRecord(java.lang.Integer userId, java.lang.Integer beerId) {
		super(com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER);

		setValue(0, userId);
		setValue(1, beerId);
	}
}
