/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FavoriteBeerRecord extends org.jooq.impl.TableRecordImpl<com.github.drinking_buddies.jooq.tables.records.FavoriteBeerRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1513016016;

	/**
	 * Setter for <code>favorite_beer.id_user</code>. 
	 */
	public void setIdUser(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>favorite_beer.id_user</code>. 
	 */
	public java.lang.Integer getIdUser() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>favorite_beer.id_beer</code>. 
	 */
	public void setIdBeer(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>favorite_beer.id_beer</code>. 
	 */
	public java.lang.Integer getIdBeer() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER.ID_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER.ID_BEER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getIdUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getIdBeer();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FavoriteBeerRecord
	 */
	public FavoriteBeerRecord() {
		super(com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER);
	}

	/**
	 * Create a detached, initialised FavoriteBeerRecord
	 */
	public FavoriteBeerRecord(java.lang.Integer idUser, java.lang.Integer idBeer) {
		super(com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER);

		setValue(0, idUser);
		setValue(1, idBeer);
	}
}
