/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.drinking_buddies.jooq.tables.records.UserRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Float, java.lang.Float, java.lang.String, byte[]> {

	private static final long serialVersionUID = 721624538;

	/**
	 * Setter for <code>user.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>user.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>user.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>user.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>user.oauth_name</code>. 
	 */
	public void setOauthName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>user.oauth_name</code>. 
	 */
	public java.lang.String getOauthName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>user.oauth_provider</code>. 
	 */
	public void setOauthProvider(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>user.oauth_provider</code>. 
	 */
	public java.lang.String getOauthProvider() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>user.location_x</code>. 
	 */
	public void setLocationX(java.lang.Float value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>user.location_x</code>. 
	 */
	public java.lang.Float getLocationX() {
		return (java.lang.Float) getValue(4);
	}

	/**
	 * Setter for <code>user.location_y</code>. 
	 */
	public void setLocationY(java.lang.Float value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>user.location_y</code>. 
	 */
	public java.lang.Float getLocationY() {
		return (java.lang.Float) getValue(5);
	}

	/**
	 * Setter for <code>user.birthdate</code>. 
	 */
	public void setBirthdate(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>user.birthdate</code>. 
	 */
	public java.lang.String getBirthdate() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>user.picture</code>. 
	 */
	public void setPicture(byte[] value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>user.picture</code>. 
	 */
	public byte[] getPicture() {
		return (byte[]) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Float, java.lang.Float, java.lang.String, byte[]> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Float, java.lang.Float, java.lang.String, byte[]> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.drinking_buddies.jooq.tables.User.USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.github.drinking_buddies.jooq.tables.User.USER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.drinking_buddies.jooq.tables.User.USER.OAUTH_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.github.drinking_buddies.jooq.tables.User.USER.OAUTH_PROVIDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Float> field5() {
		return com.github.drinking_buddies.jooq.tables.User.USER.LOCATION_X;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Float> field6() {
		return com.github.drinking_buddies.jooq.tables.User.USER.LOCATION_Y;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.github.drinking_buddies.jooq.tables.User.USER.BIRTHDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field8() {
		return com.github.drinking_buddies.jooq.tables.User.USER.PICTURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getOauthName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getOauthProvider();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Float value5() {
		return getLocationX();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Float value6() {
		return getLocationY();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getBirthdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value8() {
		return getPicture();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(com.github.drinking_buddies.jooq.tables.User.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(java.lang.Integer id, java.lang.String name, java.lang.String oauthName, java.lang.String oauthProvider, java.lang.Float locationX, java.lang.Float locationY, java.lang.String birthdate, byte[] picture) {
		super(com.github.drinking_buddies.jooq.tables.User.USER);

		setValue(0, id);
		setValue(1, name);
		setValue(2, oauthName);
		setValue(3, oauthProvider);
		setValue(4, locationX);
		setValue(5, locationY);
		setValue(6, birthdate);
		setValue(7, picture);
	}
}
