/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BarComment extends org.jooq.impl.TableImpl<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord> {

	private static final long serialVersionUID = 2116662596;

	/**
	 * The singleton instance of <code>bar_comment</code>
	 */
	public static final com.github.drinking_buddies.jooq.tables.BarComment BAR_COMMENT = new com.github.drinking_buddies.jooq.tables.BarComment();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord> getRecordType() {
		return com.github.drinking_buddies.jooq.tables.records.BarCommentRecord.class;
	}

	/**
	 * The column <code>bar_comment.id</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>bar_comment.user_id</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>bar_comment.text</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>bar_comment.timestamp</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord, java.lang.String> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.CHAR.length(16), this);

	/**
	 * Create a <code>bar_comment</code> table reference
	 */
	public BarComment() {
		super("bar_comment", com.github.drinking_buddies.jooq.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>bar_comment</code> table reference
	 */
	public BarComment(java.lang.String alias) {
		super(alias, com.github.drinking_buddies.jooq.DefaultSchema.DEFAULT_SCHEMA, com.github.drinking_buddies.jooq.tables.BarComment.BAR_COMMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord> getPrimaryKey() {
		return com.github.drinking_buddies.jooq.Keys.PK_BAR_COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord>>asList(com.github.drinking_buddies.jooq.Keys.PK_BAR_COMMENT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.drinking_buddies.jooq.tables.BarComment as(java.lang.String alias) {
		return new com.github.drinking_buddies.jooq.tables.BarComment(alias);
	}
}
