/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BarScore extends org.jooq.impl.TableImpl<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord> {

	private static final long serialVersionUID = 1988852416;

	/**
	 * The singleton instance of <code>bar_score</code>
	 */
	public static final com.github.drinking_buddies.jooq.tables.BarScore BAR_SCORE = new com.github.drinking_buddies.jooq.tables.BarScore();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord> getRecordType() {
		return com.github.drinking_buddies.jooq.tables.records.BarScoreRecord.class;
	}

	/**
	 * The column <code>bar_score.id</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>bar_score.score</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord, java.lang.Float> SCORE = createField("score", org.jooq.impl.SQLDataType.REAL, this);

	/**
	 * The column <code>bar_score.post_time</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord, java.lang.String> POST_TIME = createField("post_time", org.jooq.impl.SQLDataType.CHAR.length(16), this);

	/**
	 * The column <code>bar_score.user_id</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>bar_score</code> table reference
	 */
	public BarScore() {
		super("bar_score", com.github.drinking_buddies.jooq.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>bar_score</code> table reference
	 */
	public BarScore(java.lang.String alias) {
		super(alias, com.github.drinking_buddies.jooq.DefaultSchema.DEFAULT_SCHEMA, com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord> getPrimaryKey() {
		return com.github.drinking_buddies.jooq.Keys.PK_BAR_SCORE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord>>asList(com.github.drinking_buddies.jooq.Keys.PK_BAR_SCORE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord, ?>>asList(com.github.drinking_buddies.jooq.Keys.FK_BAR_SCORE_USER_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.drinking_buddies.jooq.tables.BarScore as(java.lang.String alias) {
		return new com.github.drinking_buddies.jooq.tables.BarScore(alias);
	}
}
