/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Beer2BeerTag extends org.jooq.impl.TableImpl<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord> {

	private static final long serialVersionUID = 329312601;

	/**
	 * The singleton instance of <code>beer2_beer_tag</code>
	 */
	public static final com.github.drinking_buddies.jooq.tables.Beer2BeerTag BEER2_BEER_TAG = new com.github.drinking_buddies.jooq.tables.Beer2BeerTag();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord> getRecordType() {
		return com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord.class;
	}

	/**
	 * The column <code>beer2_beer_tag.beertag</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord, java.lang.Object> BEERTAG = createField("beertag", org.jooq.impl.DefaultDataType.getDefaultDataType("TEXT_"), this);

	/**
	 * The column <code>beer2_beer_tag.id_beer</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord, java.lang.Integer> ID_BEER = createField("id_beer", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>beer2_beer_tag</code> table reference
	 */
	public Beer2BeerTag() {
		super("beer2_beer_tag", com.github.drinking_buddies.jooq.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>beer2_beer_tag</code> table reference
	 */
	public Beer2BeerTag(java.lang.String alias) {
		super(alias, com.github.drinking_buddies.jooq.DefaultSchema.DEFAULT_SCHEMA, com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord, ?>>asList(com.github.drinking_buddies.jooq.Keys.FK_BEER2_BEER_TAG_BEER_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.drinking_buddies.jooq.tables.Beer2BeerTag as(java.lang.String alias) {
		return new com.github.drinking_buddies.jooq.tables.Beer2BeerTag(alias);
	}
}
