/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BeerTag extends org.jooq.impl.TableImpl<com.github.drinking_buddies.jooq.tables.records.BeerTagRecord> {

	private static final long serialVersionUID = -313742131;

	/**
	 * The singleton instance of <code>beer_tag</code>
	 */
	public static final com.github.drinking_buddies.jooq.tables.BeerTag BEER_TAG = new com.github.drinking_buddies.jooq.tables.BeerTag();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.drinking_buddies.jooq.tables.records.BeerTagRecord> getRecordType() {
		return com.github.drinking_buddies.jooq.tables.records.BeerTagRecord.class;
	}

	/**
	 * The column <code>beer_tag.name</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.BeerTagRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>beer_tag</code> table reference
	 */
	public BeerTag() {
		super("beer_tag", com.github.drinking_buddies.jooq.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>beer_tag</code> table reference
	 */
	public BeerTag(java.lang.String alias) {
		super(alias, com.github.drinking_buddies.jooq.DefaultSchema.DEFAULT_SCHEMA, com.github.drinking_buddies.jooq.tables.BeerTag.BEER_TAG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BeerTagRecord> getPrimaryKey() {
		return com.github.drinking_buddies.jooq.Keys.PK_BEER_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BeerTagRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BeerTagRecord>>asList(com.github.drinking_buddies.jooq.Keys.PK_BEER_TAG);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.drinking_buddies.jooq.tables.BeerTag as(java.lang.String alias) {
		return new com.github.drinking_buddies.jooq.tables.BeerTag(alias);
	}
}
