/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FavoriteBar extends org.jooq.impl.TableImpl<com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord> {

	private static final long serialVersionUID = 1449218613;

	/**
	 * The singleton instance of <code>favorite_bar</code>
	 */
	public static final com.github.drinking_buddies.jooq.tables.FavoriteBar FAVORITE_BAR = new com.github.drinking_buddies.jooq.tables.FavoriteBar();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord> getRecordType() {
		return com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord.class;
	}

	/**
	 * The column <code>favorite_bar.id_user</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord, java.lang.Integer> ID_USER = createField("id_user", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>favorite_bar.id_bar</code>. 
	 */
	public final org.jooq.TableField<com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord, java.lang.Integer> ID_BAR = createField("id_bar", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>favorite_bar</code> table reference
	 */
	public FavoriteBar() {
		super("favorite_bar", com.github.drinking_buddies.jooq.DefaultSchema.DEFAULT_SCHEMA);
	}

	/**
	 * Create an aliased <code>favorite_bar</code> table reference
	 */
	public FavoriteBar(java.lang.String alias) {
		super(alias, com.github.drinking_buddies.jooq.DefaultSchema.DEFAULT_SCHEMA, com.github.drinking_buddies.jooq.tables.FavoriteBar.FAVORITE_BAR);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord, ?>>asList(com.github.drinking_buddies.jooq.Keys.FK_FAVORITE_BAR_USER_1, com.github.drinking_buddies.jooq.Keys.FK_FAVORITE_BAR_BAR_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.drinking_buddies.jooq.tables.FavoriteBar as(java.lang.String alias) {
		return new com.github.drinking_buddies.jooq.tables.FavoriteBar(alias);
	}
}
