/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -697929245;

	/**
	 * The singleton instance of <code></code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.github.drinking_buddies.jooq.tables.Address.ADDRESS,
			com.github.drinking_buddies.jooq.tables.Bar.BAR,
			com.github.drinking_buddies.jooq.tables.Bar2BarComment.BAR2_BAR_COMMENT,
			com.github.drinking_buddies.jooq.tables.Bar2BarScore.BAR2_BAR_SCORE,
			com.github.drinking_buddies.jooq.tables.BarComment.BAR_COMMENT,
			com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE,
			com.github.drinking_buddies.jooq.tables.Beer.BEER,
			com.github.drinking_buddies.jooq.tables.Beer2Bar.BEER2_BAR,
			com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG,
			com.github.drinking_buddies.jooq.tables.BeerTag.BEER_TAG,
			com.github.drinking_buddies.jooq.tables.Buddy.BUDDY,
			com.github.drinking_buddies.jooq.tables.FavoriteBar.FAVORITE_BAR,
			com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER,
			com.github.drinking_buddies.jooq.tables.Review.REVIEW,
			com.github.drinking_buddies.jooq.tables.ReviewComment.REVIEW_COMMENT,
			com.github.drinking_buddies.jooq.tables.User.USER);
	}
}
