/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.AddressRecord> PK_ADDRESS = UniqueKeys0.PK_ADDRESS;
	public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarRecord> PK_BAR = UniqueKeys0.PK_BAR;
	public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord> PK_BAR_COMMENT = UniqueKeys0.PK_BAR_COMMENT;
	public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord> PK_BAR_SCORE = UniqueKeys0.PK_BAR_SCORE;
	public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BeerRecord> PK_BEER = UniqueKeys0.PK_BEER;
	public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BeerTagRecord> PK_BEER_TAG = UniqueKeys0.PK_BEER_TAG;
	public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.ReviewRecord> PK_REVIEW = UniqueKeys0.PK_REVIEW;
	public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.ReviewCommentRecord> PK_REVIEW_COMMENT = UniqueKeys0.PK_REVIEW_COMMENT;
	public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.UserRecord> PK_USER = UniqueKeys0.PK_USER;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.BarRecord, com.github.drinking_buddies.jooq.tables.records.AddressRecord> FK_BAR_ADDRESS_1 = ForeignKeys0.FK_BAR_ADDRESS_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Bar2BarCommentRecord, com.github.drinking_buddies.jooq.tables.records.BarCommentRecord> FK_BAR2_BAR_COMMENT_BAR_COMMENT_1 = ForeignKeys0.FK_BAR2_BAR_COMMENT_BAR_COMMENT_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Bar2BarCommentRecord, com.github.drinking_buddies.jooq.tables.records.BarRecord> FK_BAR2_BAR_COMMENT_BAR_1 = ForeignKeys0.FK_BAR2_BAR_COMMENT_BAR_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Bar2BarScoreRecord, com.github.drinking_buddies.jooq.tables.records.BarRecord> FK_BAR2_BAR_SCORE_BAR_1 = ForeignKeys0.FK_BAR2_BAR_SCORE_BAR_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Bar2BarScoreRecord, com.github.drinking_buddies.jooq.tables.records.BarScoreRecord> FK_BAR2_BAR_SCORE_BAR_SCORE_1 = ForeignKeys0.FK_BAR2_BAR_SCORE_BAR_SCORE_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_BAR_SCORE_USER_1 = ForeignKeys0.FK_BAR_SCORE_USER_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Beer2BarRecord, com.github.drinking_buddies.jooq.tables.records.BeerRecord> FK_BEER2_BAR_BEER_1 = ForeignKeys0.FK_BEER2_BAR_BEER_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Beer2BarRecord, com.github.drinking_buddies.jooq.tables.records.BarRecord> FK_BEER2_BAR_BAR_1 = ForeignKeys0.FK_BEER2_BAR_BAR_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord, com.github.drinking_buddies.jooq.tables.records.BeerTagRecord> FK_BEER2_BEER_TAG_BEER_TAG_1 = ForeignKeys0.FK_BEER2_BEER_TAG_BEER_TAG_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord, com.github.drinking_buddies.jooq.tables.records.BeerRecord> FK_BEER2_BEER_TAG_BEER_1 = ForeignKeys0.FK_BEER2_BEER_TAG_BEER_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.BuddyRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_BUDDY_USER_2 = ForeignKeys0.FK_BUDDY_USER_2;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.BuddyRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_BUDDY_USER_1 = ForeignKeys0.FK_BUDDY_USER_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_FAVORITE_BAR_USER_1 = ForeignKeys0.FK_FAVORITE_BAR_USER_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord, com.github.drinking_buddies.jooq.tables.records.BarRecord> FK_FAVORITE_BAR_BAR_1 = ForeignKeys0.FK_FAVORITE_BAR_BAR_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.FavoriteBeerRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_FAVORITE_BEER_USER_1 = ForeignKeys0.FK_FAVORITE_BEER_USER_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.FavoriteBeerRecord, com.github.drinking_buddies.jooq.tables.records.BeerRecord> FK_FAVORITE_BEER_BEER_1 = ForeignKeys0.FK_FAVORITE_BEER_BEER_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.ReviewRecord, com.github.drinking_buddies.jooq.tables.records.BeerRecord> FK_REVIEW_BEER_1 = ForeignKeys0.FK_REVIEW_BEER_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.ReviewRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_REVIEW_USER_1 = ForeignKeys0.FK_REVIEW_USER_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.ReviewCommentRecord, com.github.drinking_buddies.jooq.tables.records.ReviewRecord> FK_REVIEW_COMMENT_REVIEW_1 = ForeignKeys0.FK_REVIEW_COMMENT_REVIEW_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.ReviewCommentRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_REVIEW_COMMENT_USER_1 = ForeignKeys0.FK_REVIEW_COMMENT_USER_1;
	public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.UserRecord, com.github.drinking_buddies.jooq.tables.records.BarRecord> FK_USER_BAR_1 = ForeignKeys0.FK_USER_BAR_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.AddressRecord> PK_ADDRESS = createUniqueKey(com.github.drinking_buddies.jooq.tables.Address.ADDRESS, com.github.drinking_buddies.jooq.tables.Address.ADDRESS.ID);
		public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarRecord> PK_BAR = createUniqueKey(com.github.drinking_buddies.jooq.tables.Bar.BAR, com.github.drinking_buddies.jooq.tables.Bar.BAR.ID);
		public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarCommentRecord> PK_BAR_COMMENT = createUniqueKey(com.github.drinking_buddies.jooq.tables.BarComment.BAR_COMMENT, com.github.drinking_buddies.jooq.tables.BarComment.BAR_COMMENT.ID);
		public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord> PK_BAR_SCORE = createUniqueKey(com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE, com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE.ID);
		public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BeerRecord> PK_BEER = createUniqueKey(com.github.drinking_buddies.jooq.tables.Beer.BEER, com.github.drinking_buddies.jooq.tables.Beer.BEER.ID);
		public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.BeerTagRecord> PK_BEER_TAG = createUniqueKey(com.github.drinking_buddies.jooq.tables.BeerTag.BEER_TAG, com.github.drinking_buddies.jooq.tables.BeerTag.BEER_TAG.ID);
		public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.ReviewRecord> PK_REVIEW = createUniqueKey(com.github.drinking_buddies.jooq.tables.Review.REVIEW, com.github.drinking_buddies.jooq.tables.Review.REVIEW.ID);
		public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.ReviewCommentRecord> PK_REVIEW_COMMENT = createUniqueKey(com.github.drinking_buddies.jooq.tables.ReviewComment.REVIEW_COMMENT, com.github.drinking_buddies.jooq.tables.ReviewComment.REVIEW_COMMENT.ID);
		public static final org.jooq.UniqueKey<com.github.drinking_buddies.jooq.tables.records.UserRecord> PK_USER = createUniqueKey(com.github.drinking_buddies.jooq.tables.User.USER, com.github.drinking_buddies.jooq.tables.User.USER.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.BarRecord, com.github.drinking_buddies.jooq.tables.records.AddressRecord> FK_BAR_ADDRESS_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_ADDRESS, com.github.drinking_buddies.jooq.tables.Bar.BAR, com.github.drinking_buddies.jooq.tables.Bar.BAR.ADDRESS_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Bar2BarCommentRecord, com.github.drinking_buddies.jooq.tables.records.BarCommentRecord> FK_BAR2_BAR_COMMENT_BAR_COMMENT_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BAR_COMMENT, com.github.drinking_buddies.jooq.tables.Bar2BarComment.BAR2_BAR_COMMENT, com.github.drinking_buddies.jooq.tables.Bar2BarComment.BAR2_BAR_COMMENT.BAR_COMMENT_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Bar2BarCommentRecord, com.github.drinking_buddies.jooq.tables.records.BarRecord> FK_BAR2_BAR_COMMENT_BAR_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BAR, com.github.drinking_buddies.jooq.tables.Bar2BarComment.BAR2_BAR_COMMENT, com.github.drinking_buddies.jooq.tables.Bar2BarComment.BAR2_BAR_COMMENT.BAR_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Bar2BarScoreRecord, com.github.drinking_buddies.jooq.tables.records.BarRecord> FK_BAR2_BAR_SCORE_BAR_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BAR, com.github.drinking_buddies.jooq.tables.Bar2BarScore.BAR2_BAR_SCORE, com.github.drinking_buddies.jooq.tables.Bar2BarScore.BAR2_BAR_SCORE.BAR_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Bar2BarScoreRecord, com.github.drinking_buddies.jooq.tables.records.BarScoreRecord> FK_BAR2_BAR_SCORE_BAR_SCORE_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BAR_SCORE, com.github.drinking_buddies.jooq.tables.Bar2BarScore.BAR2_BAR_SCORE, com.github.drinking_buddies.jooq.tables.Bar2BarScore.BAR2_BAR_SCORE.BAR_SCORE_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.BarScoreRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_BAR_SCORE_USER_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_USER, com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE, com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE.USER_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Beer2BarRecord, com.github.drinking_buddies.jooq.tables.records.BeerRecord> FK_BEER2_BAR_BEER_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BEER, com.github.drinking_buddies.jooq.tables.Beer2Bar.BEER2_BAR, com.github.drinking_buddies.jooq.tables.Beer2Bar.BEER2_BAR.BEER_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Beer2BarRecord, com.github.drinking_buddies.jooq.tables.records.BarRecord> FK_BEER2_BAR_BAR_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BAR, com.github.drinking_buddies.jooq.tables.Beer2Bar.BEER2_BAR, com.github.drinking_buddies.jooq.tables.Beer2Bar.BEER2_BAR.BAR_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord, com.github.drinking_buddies.jooq.tables.records.BeerTagRecord> FK_BEER2_BEER_TAG_BEER_TAG_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BEER_TAG, com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG, com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG.BEER_TAG_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.Beer2BeerTagRecord, com.github.drinking_buddies.jooq.tables.records.BeerRecord> FK_BEER2_BEER_TAG_BEER_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BEER, com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG, com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG.BEER_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.BuddyRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_BUDDY_USER_2 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_USER, com.github.drinking_buddies.jooq.tables.Buddy.BUDDY, com.github.drinking_buddies.jooq.tables.Buddy.BUDDY.USER_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.BuddyRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_BUDDY_USER_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_USER, com.github.drinking_buddies.jooq.tables.Buddy.BUDDY, com.github.drinking_buddies.jooq.tables.Buddy.BUDDY.BUDDY_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_FAVORITE_BAR_USER_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_USER, com.github.drinking_buddies.jooq.tables.FavoriteBar.FAVORITE_BAR, com.github.drinking_buddies.jooq.tables.FavoriteBar.FAVORITE_BAR.USER_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.FavoriteBarRecord, com.github.drinking_buddies.jooq.tables.records.BarRecord> FK_FAVORITE_BAR_BAR_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BAR, com.github.drinking_buddies.jooq.tables.FavoriteBar.FAVORITE_BAR, com.github.drinking_buddies.jooq.tables.FavoriteBar.FAVORITE_BAR.BAR_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.FavoriteBeerRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_FAVORITE_BEER_USER_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_USER, com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER, com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER.USER_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.FavoriteBeerRecord, com.github.drinking_buddies.jooq.tables.records.BeerRecord> FK_FAVORITE_BEER_BEER_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BEER, com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER, com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER.BEER_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.ReviewRecord, com.github.drinking_buddies.jooq.tables.records.BeerRecord> FK_REVIEW_BEER_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BEER, com.github.drinking_buddies.jooq.tables.Review.REVIEW, com.github.drinking_buddies.jooq.tables.Review.REVIEW.BEER_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.ReviewRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_REVIEW_USER_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_USER, com.github.drinking_buddies.jooq.tables.Review.REVIEW, com.github.drinking_buddies.jooq.tables.Review.REVIEW.USER_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.ReviewCommentRecord, com.github.drinking_buddies.jooq.tables.records.ReviewRecord> FK_REVIEW_COMMENT_REVIEW_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_REVIEW, com.github.drinking_buddies.jooq.tables.ReviewComment.REVIEW_COMMENT, com.github.drinking_buddies.jooq.tables.ReviewComment.REVIEW_COMMENT.REVIEW_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.ReviewCommentRecord, com.github.drinking_buddies.jooq.tables.records.UserRecord> FK_REVIEW_COMMENT_USER_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_USER, com.github.drinking_buddies.jooq.tables.ReviewComment.REVIEW_COMMENT, com.github.drinking_buddies.jooq.tables.ReviewComment.REVIEW_COMMENT.USER_ID);
		public static final org.jooq.ForeignKey<com.github.drinking_buddies.jooq.tables.records.UserRecord, com.github.drinking_buddies.jooq.tables.records.BarRecord> FK_USER_BAR_1 = createForeignKey(com.github.drinking_buddies.jooq.Keys.PK_BAR, com.github.drinking_buddies.jooq.tables.User.USER, com.github.drinking_buddies.jooq.tables.User.USER.BAR_ID);
	}
}
