/**
 * This class is generated by jOOQ
 */
package com.github.drinking_buddies.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in 
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table address
	 */
	public static final com.github.drinking_buddies.jooq.tables.Address ADDRESS = com.github.drinking_buddies.jooq.tables.Address.ADDRESS;

	/**
	 * The table bar
	 */
	public static final com.github.drinking_buddies.jooq.tables.Bar BAR = com.github.drinking_buddies.jooq.tables.Bar.BAR;

	/**
	 * The table bar2_bar_comment
	 */
	public static final com.github.drinking_buddies.jooq.tables.Bar2BarComment BAR2_BAR_COMMENT = com.github.drinking_buddies.jooq.tables.Bar2BarComment.BAR2_BAR_COMMENT;

	/**
	 * The table bar2_bar_score
	 */
	public static final com.github.drinking_buddies.jooq.tables.Bar2BarScore BAR2_BAR_SCORE = com.github.drinking_buddies.jooq.tables.Bar2BarScore.BAR2_BAR_SCORE;

	/**
	 * The table bar_comment
	 */
	public static final com.github.drinking_buddies.jooq.tables.BarComment BAR_COMMENT = com.github.drinking_buddies.jooq.tables.BarComment.BAR_COMMENT;

	/**
	 * The table bar_score
	 */
	public static final com.github.drinking_buddies.jooq.tables.BarScore BAR_SCORE = com.github.drinking_buddies.jooq.tables.BarScore.BAR_SCORE;

	/**
	 * The table beer
	 */
	public static final com.github.drinking_buddies.jooq.tables.Beer BEER = com.github.drinking_buddies.jooq.tables.Beer.BEER;

	/**
	 * The table beer2_bar
	 */
	public static final com.github.drinking_buddies.jooq.tables.Beer2Bar BEER2_BAR = com.github.drinking_buddies.jooq.tables.Beer2Bar.BEER2_BAR;

	/**
	 * The table beer2_beer_tag
	 */
	public static final com.github.drinking_buddies.jooq.tables.Beer2BeerTag BEER2_BEER_TAG = com.github.drinking_buddies.jooq.tables.Beer2BeerTag.BEER2_BEER_TAG;

	/**
	 * The table beer_tag
	 */
	public static final com.github.drinking_buddies.jooq.tables.BeerTag BEER_TAG = com.github.drinking_buddies.jooq.tables.BeerTag.BEER_TAG;

	/**
	 * The table buddy
	 */
	public static final com.github.drinking_buddies.jooq.tables.Buddy BUDDY = com.github.drinking_buddies.jooq.tables.Buddy.BUDDY;

	/**
	 * The table favorite_bar
	 */
	public static final com.github.drinking_buddies.jooq.tables.FavoriteBar FAVORITE_BAR = com.github.drinking_buddies.jooq.tables.FavoriteBar.FAVORITE_BAR;

	/**
	 * The table favorite_beer
	 */
	public static final com.github.drinking_buddies.jooq.tables.FavoriteBeer FAVORITE_BEER = com.github.drinking_buddies.jooq.tables.FavoriteBeer.FAVORITE_BEER;

	/**
	 * The table review
	 */
	public static final com.github.drinking_buddies.jooq.tables.Review REVIEW = com.github.drinking_buddies.jooq.tables.Review.REVIEW;

	/**
	 * The table review_comment
	 */
	public static final com.github.drinking_buddies.jooq.tables.ReviewComment REVIEW_COMMENT = com.github.drinking_buddies.jooq.tables.ReviewComment.REVIEW_COMMENT;

	/**
	 * The table user
	 */
	public static final com.github.drinking_buddies.jooq.tables.User USER = com.github.drinking_buddies.jooq.tables.User.USER;
}
